name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.11'
          otp-version: '22.3'
      - name: Install dependencies
        run: mix deps.get
      -
        name: Generate page
        run: mix cyberspace.write priv/index.html
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: priv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
